name: shops
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.7+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  dio: ^5.9.0
  freezed: ^3.2.3
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  go_router: ^16.2.1
  connectivity_plus: ^7.0.0
  mask_text_input_formatter: ^2.9.0
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.1.0
  icons_flutter: ^0.0.5
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
